### ISSUE TITLE
Please make the AppImage available for download

### ISSUE THREAD

**Issue by probonopd** [privet56/qBoss#1]
Please make the AppImage available for download on GitHub Releases, thank you.

**Comment by privet56** [comment]
sorry, no linux/macOS releases planned

**Comment by probonopd** [comment]
This seems to suggest otherwise:

https://github.com/privet56/qBoss/blob/1a71e13d045a1f03ae086a633ef07c5707e513de/README.md#L229

**Comment by privet56** [comment]
You are right:
I did not separate the app-description from my general Qt-cheatsheet clearly enough in the README.md
Now I moved the cheat sheet in a new file:
https://github.com/privet56/qBoss/blob/master/qt_cheatsheet.md
and left only the app description in the README
https://github.com/privet56/qBoss/blob/master/README.md
